# docker-compose.yml
version: '3.8'

services:
  trader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hft-trader
    volumes:
      - ./config:/app/etc/TriangularArbitrageSystem/config:ro
      - ./logs:/app/logs
    environment:
      - CONFIG_ENV=prod
      - LOG_LEVEL=info
      - CONFIG_PATH=/app/etc/TriangularArbitrageSystem/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    network_mode: host
    cap_add:
      - SYS_NICE

  prometheus:
    image: prom/prometheus:latest
    container_name: hft-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  dashboard:
    image: grafana/grafana:latest
    container_name: hft-dashboard
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-storage:
