name: HFT CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/**'
      - 'Dockerfile'
      - 'CMakeLists.txt'
      - 'requirements.txt'
  pull_request:
    branches:
      - main
      - develop

env:
  PYTHON_VERSION: '3.11'
  BENCHMARK_THRESHOLD_US: 100    # μs latency threshold for router
  ARTIFACTS_PATH: benchmark_reports

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libzmq3-dev python3-pip

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure & Build C++
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release -j$(nproc)

      - name: Run Unit Tests (CTest)
        run: |
          cd build
          ctest --output-on-failure

      - name: Run Pytest Unit & Integration
        run: |
          pytest tests/unit tests/integration --tb=short -v

      - name: Performance Benchmark (Binary)
        run: |
          cd build
          ./tests/performance/latency_benchmark

      - name: Benchmark Performance (Pytest)
        run: |
          pytest tests/performance/test_performance.py --tb=short --benchmark-save=router

      - name: Evaluate Latency Threshold
        run: |
          mean_latency=$(pytest tests/performance/test_performance.py \
                          --benchmark-only \
                          --benchmark-save-data \
                          | grep "Mean latency" | grep -oE "[0-9]+\.[0-9]+")
          echo "Mean latency: ${mean_latency} μs"
          if (( $(echo "$mean_latency > $BENCHMARK_THRESHOLD_US" | bc -l) )); then
            echo "⚠️ Latency (${mean_latency}μs) exceeds threshold (${BENCHMARK_THRESHOLD_US}μs)!"
            exit 1
          fi

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: hft-system:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Integration Tests (Docker Compose)
        run: |
          docker-compose -f docker-compose.test.yml up --abort-on-container-exit

      - name: Run Backtests
        run: |
          python3 backtest/run_backtest.py --config config/test/backtest_config.json

      - name: Upload Performance & Benchmark Reports
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACTS_PATH }}
          path: |
            build/tests/performance/reports/
            backtest/results/

  canary-deployment:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    environment: production

    steps:
      - name: Build Canary Docker Image
        run: docker build -t quant-backtester:canary .

      - name: Run Canary Simulation
        run: |
          docker run --rm \
            -v $(pwd)/test_data:/app/data \
            quant-backtester:canary /app/build/QuantTickEngine

      - name: Require Manual Approval
        uses: hmarr/auto-approve-action@v3
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  alert-on-failure:
    needs: build-and-test
    if: failure()
    runs-on: ubuntu-22.04

    steps:
      - name: Send Slack Alert
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,message,commit,author,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  rollback-if-latency-violation:
    needs: build-and-test
    if: failure()
    runs-on: ubuntu-22.04

    steps:
      - name: Rollback Last Commit
        run: |
          git checkout main
          git revert HEAD --no-edit
          git push origin main || echo "⚠️ Manual intervention required"
